#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 17 16:00:14 2018

@author: tomas
"""

import jnius_config
import glob
import os
import subprocess

jhome = subprocess.run(["/home/tomas/Fiji.app/ImageJ-linux64",
                        "--print-java-home"],stdout=subprocess.PIPE)
jhome = jhome.stdout.decode().strip()
os.environ["JAVA_HOME"] = jhome

jars = glob.glob("/home/tomas/Fiji.app/**/*.jar",recursive=True)
jnius_config.set_classpath(*jars)
import jnius

Jclass = jnius.autoclass
String = Jclass("java.lang.String")
#System = Jclass('java.lang.System')


class ij:
    CompositeImage = Jclass("ij.CompositeImage")
    Executer = Jclass("ij.Executer")
    IJ = Jclass("ij.IJ")
    ImageJ = Jclass("ij.ImageJ")
    ImageJApplet = Jclass("ij.ImageJApplet")
    ImagePlus = Jclass("ij.ImagePlus")
    ImageStack = Jclass("ij.ImageStack")
    LookUpTable = Jclass("ij.LookUpTable")
    Macro = Jclass("ij.Macro")
    Menus = Jclass("ij.Menus")
    OtherInstance = Jclass("ij.OtherInstance")
    Prefs = Jclass("ij.Prefs")
    RecentOpener = Jclass("ij.RecentOpener")
    Undo = Jclass("ij.Undo")
    VirtualStack = Jclass("ij.VirtualStack")
    WindowManager = Jclass("ij.WindowManager")
    
    class gui:
        jclass = lambda string : Jclass("ij.gui.{}".format(string))
        Arrow = jclass("Arrow")
        ColorChooser = jclass("ColorChooser")
        EllipseRoi = jclass("EllipseRoi")
        FreehandRoi = jclass("FreehandRoi")
        GenericDialog = jclass("GenericDialog")
        GUI = jclass("GUI")
        HistogramWindow = jclass("HistogramWindow")
        HTMLDialog = jclass("HTMLDialog")
        ImageCanvas = jclass("ImageCanvas")
        ImageLayout = jclass("ImageLayout")
        ImagePanel = jclass("ImagePanel")
        ImageRoi = jclass("ImageRoi")
        ImageWindow = jclass("ImageWindow")
        Line = jclass("Line")
        MessageDialog = jclass("MessageDialog")
        MultiLineLabel = jclass("MultiLineLabel")
        NewImage = jclass("NewImage")
        NonBlockingGenericDialog = jclass("NonBlockingGenericDialog")
        OvalRoi = jclass("OvalRoi")
        Overlay = jclass("Overlay")
        Plot = jclass("Plot")
        PlotCanvas = jclass("PlotCanvas")
        #PlotContentsStyleDialog = jclass("PlotContentsStyleDialog")
        PlotDialog = jclass("PlotDialog")
        PlotVirtualStack = jclass("PlotVirtualStack")
        PlotWindow = jclass("PlotWindow")
        PointRoi = jclass("PointRoi")
        PolygonRoi = jclass("PolygonRoi")
        ProfilePlot = jclass("ProfilePlot")
        ProgressBar = jclass("ProgressBar")
        Roi = jclass("Roi")
        RoiProperties = jclass("RoiProperties")
        RotatedRectRoi = jclass("RotatedRectRoi")
        SaveChangesDialog = jclass("SaveChangesDialog")
        ScrollbarWithLabel = jclass("ScrollbarWithLabel")
        StackWindow = jclass("StackWindow")
        TextRoi = jclass("TextRoi")
        Toolbar = jclass("Toolbar")
        TrimmedButon = jclass("TrimmedButton")
        WaitForUserDialog = jclass("WaitForUserDialog")
        Wand = jclass("Wand")
        YesNoCancelDialog = jclass("YesNoCancelDialog")
    class io:
        jclass = lambda classname : Jclass("ij.io.{}".format(classname))
        BitBuffer = jclass("BitBuffer")
        DirectoryChooser = jclass("DirectoryChooser")
        FileInfo = jclass("FileInfo")
        FileOpener = jclass("FileOpener")
        FileSaver = jclass("FileSaver")
        ImageReader = jclass("ImageReader")
        ImageWriter = jclass("ImageWriter")
        ImportDialog = jclass("ImportDialog")
        LogStream = jclass("LogStream")
        OpenDialog = jclass("OpenDialog")
        Opener = jclass("Opener")
        PluginClassLoader = jclass("PluginClassLoader")
        RandomAccessStream = jclass("RandomAccessStream")
        RoiDecoder = jclass("RoiDecoder")
        RoiEncoder = jclass("RoiEncoder")
        SaveDialog = jclass("SaveDialog")
        TextEncoder = jclass("TextEncoder")
        TiffDecoder = jclass("TiffDecoder")
        TiffEncoder = jclass("TiffEncoder")
    class macro:
        jclass = lambda classname : Jclass("ij.macro.{}".format(classname))
        ExtensionDescriptor = jclass("ExtensionDescriptor")
        FunctionFinder = jclass("FunctionFinder")
        Functions = jclass("Functions")
        Interpreter = jclass("Interpreter")
        MacroRunner = jclass("MacroRunner")
        Program = jclass("Program")
        StartupRunner = jclass("StartupRunner")
        Symbol = jclass("Symbol")
        Tokenizer = jclass("Tokenizer")
        Variable = jclass("Variable")
    class measure:
        jclass = lambda classname : Jclass("ij.measure.{}".format(classname))
        Calibration = jclass("Calibration")
        CurveFitter = jclass("CurveFitter")
        Minimizer = jclass("Minimizer")
        ResultsTable = jclass("ResultsTable")
        ResultsTableMacros = jclass("ResultsTableMacros")
        SplineFitter = jclass("SplineFitter")
    class plugin:
        jclass = lambda classname : Jclass("ij.plugin.{}".format(classname))
        AboutBox = jclass("AboutBox")
        Animator = jclass("Animator")
        AppearanceOptions = jclass("AppearanceOptions")
        ArrowToolOptions = jclass("ArrowToolOptions")
        AVI_Reader = jclass("AVI_Reader")
        BatchConverter = jclass("BatchConverter")
        BatchMeasure = jclass("BatchMeasure")
        BatchProcessor = jclass("BatchProcessor")
        Binner = jclass("Binner")
        BMP_Reader = jclass("BMP_Reader")
        BMP_Writer = jclass("BMP_Writer")
        BrowserLauncher = jclass("BrowserLauncher")
        CalibrationBar = jclass("CalibrationBar")
        CanvasResizer = jclass("CanvasResizer")
        ChannelArranger = jclass("ChannelArranger")
        ChannelSplitter = jclass("ChannelSplitter")
        CircularRoiMaker = jclass("CircularRoiMaker")
        ClassChecker = jclass("ClassChecker")
        Clipboard = jclass("Clipboard")
        Colors = jclass("Colors")
        CommandFinder = jclass("CommandFinder")
        CommandLister = jclass("CommandLister")
        Commands = jclass("Commands")
        Compiler = jclass("Compiler")
        CompositeConverter = jclass("CompositeConverter")
        Concatenator = jclass("Concatenator")
        ContrastEnhancer = jclass("ContrastEnhancer")
        ControlPanel = jclass("ControlPanel")
        Converter = jclass("Converter")
        Coordinates = jclass("Coordinates")
        DICOM = jclass("DICOM")
        Distribution = jclass("Distribution")
        DragAndDrop = jclass("DragAndDrop")
        Duplicator = jclass("Duplicator")
        EventListener = jclass("EventListener")
        FFT = jclass("FFT")
        FFTMath = jclass("FFTMath")
        FileInfoVirtualStack = jclass("FileInfoVirtualStack")
        Filters3D = jclass("Filters3D")
        FITS_Reader = jclass("FITS_Reader")
        FITS_Writer = jclass("FITS_Writer")
        FolderOpener = jclass("FolderOpener")
        #GaussianBlur3D = jclass("GuassianBlur3D")
        GelAnalyzer = jclass("GelAnalyzer")
        GIF_Reader = jclass("GIF_Reader")
        Grid = jclass("Grid")
        GroupedZProjector = jclass("GroupedZProjector")
        Histogram = jclass("Histogram")
        Hotkeys = jclass("Hotkeys")
        HyperStackConverter = jclass("HyperStackConverter")
        HyperStackMaker = jclass("HyperStackMaker")
        HyperStackReducer = jclass("HyperStackReducer")
        ImageCalculator = jclass("ImageCalculator")
        ImageInfo = jclass("ImageInfo")
        ImageJ_Updater = jclass("ImageJ_Updater")
        ImagesToStack = jclass("ImagesToStack")
        JavaProperties = jclass("JavaProperties")
        JavaScriptEvaluator = jclass("JavaScriptEvaluator")
        JpegWriter = jclass("JpegWriter")
        ListVirtualStack = jclass("ListVirtualStack")
        LUT_Editor = jclass("LUT_Editor")
        LutLoader = jclass("LutLoader")
        Macro_Runner = jclass("Macro_Runner")
        MacroInstaller = jclass("MacroInstaller")
        MeasurementsWriter = jclass("MeasurementsWriter")
        Memory = jclass("Memory")
        MontageMaker = jclass("MontageMaker")
        NewPlugin = jclass("NewPlugin")
        NextImageOpener = jclass("NextImageOpener")
        Options = jclass("Options")
        #Orthagonal_Views = jclass("Orthagonal_Views")
        OverlayCommands = jclass("OverlayCommands")
        OverlayLabels = jclass("OverlayLabels")
        PGM_Reader = jclass("PGM_Reader")
        PluginInstaller = jclass("PluginInstaller")
        PlugInInterpreter = jclass("PlugInInterpreter")
        PNG_Writer = jclass("PNG_Writer")
        PNM_Writer = jclass("PNM_Writer")
        PointToolOptions = jclass("PointToolOptions")
        Profiler = jclass("Profiler")
        Projector = jclass("Projector")
        ProxySettings = jclass("ProxySettings")
        Raw = jclass("Raw")
        RectToolOptions = jclass("RectToolOptions")
        Resizer = jclass("Resizer")
        ResultsSorter = jclass("ResultsSorter")
        RGBStackConverter = jclass("RGBStackConverter")
        RGBStackMerge = jclass("RGBStackMerge")
        RoiEnlarger = jclass("RoiEnlarger")
        RoiInterpolator = jclass("RoiInterpolator")
        RoiReader = jclass("RoiReader")
        RoiRotator = jclass("RoiRotator")
        RoiScaler = jclass("RoiScaler")
        ScaleBar = jclass("ScaleBar")
        Scaler = jclass("Scaler")
        ScreenGrabber = jclass("ScreenGrabber")
        Selection = jclass("Selection")
        SimpleCommands = jclass("SimpleCommands")
        Slicer = jclass("Slicer")
        #SpecifyRoi = jclass("SpecifyRoi")
        Stack_Statistics = jclass("Stack_Statistics")
        StackCombiner = jclass("StackCombiner")
        StackEditor = jclass("StackEditor")
        StackInserter = jclass("StackInserter")
        StackMaker = jclass("StackMaker")
        StackPlotter = jclass("StackPlotter")
        StackReducer = jclass("StackReducer")
        StackReverser = jclass("StackReverser")
        StackWriter = jclass("StackWriter")
        Startup = jclass("Startup")
        Straightener = jclass("Straightener")
        #SubHyperstackMaker = jclass("SubHyperStackMaker")
        SubstackMaker = jclass("SubstackMaker")
        SurfacePlotter = jclass("SurfacePlotter")
        Text = jclass("Text")
        TextFileReader = jclass("TextFileReader")
        TextReader = jclass("TextReader")
        TextWriter = jclass("TextWriter")
        ThreadLister = jclass("ThreadLister")
        Thresholder = jclass("Thresholder")
        URLOpener = jclass("URLOpener")
        WandToolOptions = jclass("WandToolOptions")
        WindowOrganizer = jclass("WindowOrganizer")
        XY_Reader = jclass("XY_Reader")
        XYCoordinates = jclass("XYCoordinates")
        ZAxisProfiler = jclass("ZAxisProfiler")
        Zoom = jclass("Zoom")
        ZProjector = jclass("ZProjector")
        
        class _filter:
            jclass = lambda classname : Jclass("ij.plugin.filter.{}".format(classname))
            Analyzer = jclass("Analyzer")
            AVI_Writer = jclass("AVI_Writer")
            BackgroundSubtracter = jclass("BackgroundSubtracter")
            Benchmark = jclass("Benchmark")
            Binary = jclass("Binary")
            Calibrator = jclass("Calibrator")
            Convolver = jclass("Convolver")
            Duplicater = jclass("Duplicater")
            EDM = jclass("EDM")
            FFTCustomFilter = jclass("FFTCustomFilter")
            FFTFilter = jclass("FFTFilter")
            Filler = jclass("Filler")
            Filters = jclass("Filters")
            #FractalBoxCount = jclass("FractalBoxCount")
            GaussianBlur = jclass("GaussianBlur")
            ImageMath = jclass("ImageMath")
            ImageProperties = jclass("ImageProperties")
            Info = jclass("Info")
            LineGraphAnalyzer = jclass("LineGraphAnalyzer")
            LutApplier = jclass("LutApplier")
            LutViewer = jclass("LutViewer")
            MaximumFinder = jclass("MaximumFinder")
            ParticleAnalyzer = jclass("ParticleAnalyzer")
            PlugInFilterRunner = jclass("PlugInFilterRunner")
            Printer = jclass("Printer")
            RankFilters = jclass("RankFilters")
            RGBStackSplitter = jclass("RGBStackSplitter")
            RoiWriter = jclass("RoiWriter")
            Rotator = jclass("Rotator")
            SaltAndPepper = jclass("SaltAndPepper")
            ScaleDialog = jclass("ScaleDialog")
            Shadows = jclass("Shadows")
            StackLabeler = jclass("StackLabeler")
            ThresholdToSelection = jclass("ThresholdToSelection")
            Transformer = jclass("Transformer")
            Translator = jclass("Translator")
            UnsharpMask = jclass("UnsharpMask")
            Writer = jclass("Writer")
            XYWriter = jclass("XYWriter")
        
        class frame:
            jclass = lambda classname : Jclass("ij.plugin.frame.{}".format(classname))
            Channels = jclass("Channels")
            ColorPicker = jclass("ColorPicker")
            ColorThresholder = jclass("ColorThresholder")
            ContrastAdjuster = jclass("ContrastAdjuster")
            Editor = jclass("Editor")
            Fitter = jclass("Fitter")
            LineWidthAdjuster = jclass("LineWidthAdjuster")
            MemoryMonitor = jclass("MemoryMonitor")
            PasteController = jclass("PasteController")
            PlugInDialog = jclass("PlugInDialog")
            PlugInFrame = jclass("PlugInFrame")
            Recorder = jclass("Recorder")
            RoiManager = jclass("RoiManager")
            SyncWindows = jclass("SyncWindows")
            ThresholdAdjuster = jclass("ThresholdAdjuster")
        
        class tool:
            jclass = lambda classname : Jclass("ij.plugin.tool.{}".format(classname))
            ArrowTool = jclass("ArrowTool")
            BrushTool = jclass("BrushTool")
            MacroToolRunner = jclass("MacroToolRunner")
            OverlayBrushTool = jclass("OverlayBrushTool")
            PixelInspectionTool = jclass("PixelInspectionTool")
            PluginInTool = jclass("PlugInTool")
            RoiRotationTool = jclass("RoiRotationTool")
    
    class process:
        jclass = lambda classname : Jclass("ij.process.{}".format(classname))
        AutoThresholder = jclass("AutoThresholder")
        BinaryInterpolator = jclass("BinaryInterpolator")
        BinaryProcessor = jclass("BinaryProcessor")
        ByteBlitter = jclass("ByteBlitter")
        ByteStatistics = jclass("ByteStatistics")
        ColorBlitter = jclass("ColorBlitter")
        ColorProcessor = jclass("ColorProcessor")
        ColorSpaceConverter = jclass("ColorSpaceConverter")
        ColorStatistics = jclass("ColorStatistics")
        #DownsideTable = jclass("DownsideTable")
        EllipseFitter = jclass("EllipseFitter")
        FHT = jclass("FHT")
        FloatBlitter = jclass("FloatBlitter")
        FloatPolygon = jclass("FloatPolygon")
        FloatProcessor = jclass("FloatProcessor")
        FloatStatistics = jclass("FloatStatistics")
        FloodFiller = jclass("FloodFiller")
        ImageConverter = jclass("ImageConverter")
        ImageProcessor = jclass("ImageProcessor")
        ImageStatistics = jclass("ImageStatistics")
        LUT = jclass("LUT")
        MedianCut = jclass("MedianCut")
        PolygonFiller = jclass("PolygonFiller")
        ShortBlitter = jclass("ShortBlitter")
        ShortProcessor = jclass("ShortProcessor")
        ShortStatistics = jclass("ShortStatistics")
        StackConverter = jclass("StackConverter")
        StackProcessor = jclass("StackProcessor")
        StackStatistics = jclass("StackStatistics")
        TypeConverter = jclass("TypeConverter")
    
    class text:
        jclass = lambda classname : Jclass("ij.text.{}".format(classname))
        TextPanel = jclass("TextPanel")
        TextWindow = jclass("TextWindow")
    
    class util:
        jclass = lambda classname : Jclass("ij.util.{}".format(classname))
        ArrayUtil = jclass("ArrayUtil")
        DicomTools = jclass("DicomTools")
        FontUtil = jclass("FontUtil")
        IJMath = jclass("IJMath")
        Java2 = jclass("Java2")
        StringSorted = jclass("StringSorter")
        ThreadUtil = jclass("ThreadUtil")
        Toools = jclass("Tools")
        WildcardMatch = jclass("WildcardMatch")
        
